export const categories = [
  { id: 1, title: "All Categories" },
  { id: 2, title: "Art" },
  { id: 3, title: "Celebrities" },
  { id: 4, title: "Gaming" },
  { id: 5, title: "Sport" },
  { id: 6, title: "Music" },
  { id: 7, title: "Crypto" },
];

export const nftsCollection = [
  {
    id: 1,
    title: "ArtCrpto",
    value: "0.25",
    img: "/assets/f1.png",
    category: "Art",
  },
  {
    id: 2,
    title: "This NFT",
    value: "0.50",
    img: "/assets/f5.png",
    category: "Art",
  },
  {
    id: 3,
    title: "NameCrypto",
    value: "0.23",
    img: "/assets/f9.png",
    category: "Gaming",
  },
  {
    id: 4,
    title: "KingCrpto",
    value: "0.45",
    img: "/assets/f1.png",
    category: "Gaming",
  },

  {
    id: 5,
    title: "ArtCrpto",
    value: "0.25",
    img: "/assets/f5.png",
    category: "Crypto",
  },
  {
    id: 6,
    title: "KingCrpto",
    value: "0.25",
    img: "/assets/f9.png",
    category: "Celebrities",
  },
  {
    id: 7,
    title: "NameCrpto",
    value: "0.25",
    img: "/assets/f1.png",
    category: "Sport",
  },
  {
    id: 8,
    title: "ThisNFT",
    value: "0.25",
    img: "/assets/f5.png",
    category: "Music",
  },
  {
    id: 9,
    title: "ArtCrpto",
    value: "0.39",
    img: "/assets/f9.png",
    category: "Crypto",
  },
  {
    id: 10,
    title: "ArtCrpto",
    value: "0.25",
    img: "/assets/f9.png",
    category: "Music",
  },
  {
    id: 11,
    title: "KingCrpto",
    value: "0.32",
    img: "/assets/f5.png",
    category: "Crypto",
  },
  {
    id: 12,
    title: "LionCrpto",
    value: "0.25",
    img: "/assets/f1.png",
    category: "Art",
  },
  {
    id: 13,
    title: "ArtCrpto",
    value: "0.25",
    img: "/assets/f1.png",
    category: "Gaming",
  },
  {
    id: 14,
    title: "ThisCrpto",
    value: "0.25",
    img: "/assets/f5.png",
    category: "Gaming",
  },
  {
    id: 15,
    title: "HelloCrpto",
    value: "0.35",
    img: "/assets/f1.png",
    category: "Crypto",
  },
  {
    id: 16,
    title: "CyptoCrpto",
    value: "0.37",
    img: "/assets/f5.png",
    category: "Celebrities",
  },
];
